name:                game
version:             0.1.0.0
github:              "erratic-c-programmer/game"
license:             GPL3
author:              "Isaac"
maintainer:          "tux314159@gmail.com"
copyright:           "2022 Isaac \"Tux\" Yeo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erratic-c-programmer/game#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2 && < 2
- mtl >= 2.2 && < 3
- lens >= 5 && < 6
- text >= 1.2 && < 2

library:
  source-dirs: src

executables:
  game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game

tests:
  game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game
